### ISSUE TITLE
Ambiguous sentence about touch events

### ISSUE THREAD

**Issue by gregersrygg** [inma-no/advertsspec#21]
“You can not override default touch events” is not clear.

How about something like this?
“You can not prevent touch/stop/cancel touch events”

I think this rule came when we had swipe left/right for off-screen menus. This is not a good practice anymore, since iOS 7 often navigates back/forward with swipe gestures. Should we allow horizontal swiping, but not vertical? How should we describe that in the spec?

**Comment by OleSan** [comment]
Should we just agree that a 30° angle is how we define this, and update the spec with it?

**Comment by gregersrygg** [comment]
@OleSan +1
