### ISSUE TITLE
jQuery, CDN and versions

### ISSUE THREAD

**Issue by sylling** [inma-no/advertsspec#27]
Currently the spec says external JS libraries like jQuery can be loaded from Google CDN.
But what version(s)?

**Comment by OleSan** [comment]
I agree, we should include what version(s) are allowed. 

My suggestion right now would be: v1.11.2

**Comment by gregersrygg** [comment]
Correct me if I'm wrong @sveisvei, but I think the validator requires the most recent version of jQuery. I think both 1.x and 2.x are allowed, but it has to be the latest released version. This to have as good cache-hit on the script as possible (between ads).

**Comment by sveisvei** [comment]
Atm its configurable in the validator, but default is 2 latest minor versions.

**Comment by OleSan** [comment]
Picking up this again, should we just say the 2 lastest minor versions, like the validator does now?

**Comment by gregersrygg** [comment]
@OleSan :+1:
