### ISSUE TITLE
Does including GSAP library count against kB limit?

### ISSUE THREAD

**Issue by hakonom** [inma-no/advertsspec#34]
As the GSAP is now included into the spec, does this mean we can include their library from https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js without counting its size against the kB limit?

Under "Size" in the spec it only mentions jQuery which can be loaded from Google CDN without counting it against the total size of the ad, but not any other libraries. If it's now the same with GSAP, maybe it should be mentioned in the same place?

Otherwise, if the GSAP library DOES count against the kB limit, then it's impossible to use the TweenMax library (current version is 102kB minimized) before user interaction, as the current kB limit is 100.

**Comment by encruz** [comment]
Since GSAP is cached in the browser, it's downloaded only once. This also means that your still have your 100kb-limit.

**Comment by OleSan** [comment]
@hakonom Great question, I just forgot to include it. I'll fix it now, it shouldn't count against size if it use that CDN link.
